NULL =

perform-memcheck: $(TEST_PROGS) $(top_builddir)/build/valgrind-built.supp
	@for test in $(TEST_PROGS); do \
		G_SLICE=always-malloc libtool --mode=execute \
			valgrind --trace-children=no --gen-suppressions=all \
			--suppressions=$(top_builddir)/build/valgrind-built.supp \
			--leak-check=full --show-reachable=yes --num-callers=16 \
			--quiet --error-exitcode=33 \
			$(builddir)/$$test; \
	done
